export const ADMIN_COLLAPSED_SIDEBAR_WIDTH = 80;
export const ADMIN_DEFAULT_SIDEBAR_WIDTH = 256;
export const ADMIN_MIN_SIDEBAR_WIDTH = 220;
export const ADMIN_MAX_SIDEBAR_WIDTH = 420;

export const SETTINGS_DEFAULT_PREVIEW_WIDTH = 380;
export const SETTINGS_MIN_PREVIEW_WIDTH = 320;
export const SETTINGS_MAX_PREVIEW_WIDTH = 560;
