export const PLANS = {
  free: {
    id: "free",
    name: "Free",
    description: "Get started with the essentials.",
    price: 0,
    amountInPaise: 0,
    currency: "INR",
    features: {
      maxProjects: 3,
      maxSkills: 10,
      maxExperience: 3,
      maxTestimonials: 3,
      customDomain: false,
      aiWriting: false,
      allThemes: false,
      allDesignPresets: false,
      prioritySupport: false,
      analytics: false,
      resumeUpload: true,
      contactForm: true,
      seoSettings: true,
    },
    featureList: [
      "Up to 3 Projects",
      "Up to 10 Skills",
      "Up to 3 Experience entries",
      "Up to 3 Testimonials",
      "2 Theme Palettes",
      "1 Design Preset",
      "Resume Upload",
      "Contact Form",
      "Basic SEO",
    ],
  },
  pro: {
    id: "pro",
    name: "Pro",
    description: "Unlock everything. Build without limits.",
    price: 499,
    amountInPaise: 49900,
    currency: "INR",
    features: {
      maxProjects: Infinity,
      maxSkills: Infinity,
      maxExperience: Infinity,
      maxTestimonials: Infinity,
      customDomain: true,
      aiWriting: true,
      allThemes: true,
      allDesignPresets: true,
      prioritySupport: true,
      analytics: true,
      resumeUpload: true,
      contactForm: true,
      seoSettings: true,
    },
    featureList: [
      "Unlimited Projects",
      "Unlimited Skills",
      "Unlimited Experience",
      "Unlimited Testimonials",
      "All Theme Palettes",
      "All Design Presets",
      "Custom Domain",
      "AI Writing Assistant",
      "Priority Support",
      "Portfolio Analytics",
      "Resume Upload",
      "Contact Form",
      "Advanced SEO",
    ],
  },
} as const;

export type PlanId = keyof typeof PLANS;

export const PRO_ONLY_FEATURES = [
  { label: "Unlimited Projects", description: "Showcase all your work without limits" },
  { label: "Custom Domain", description: "Use your own domain name" },
  { label: "AI Writing Assistant", description: "Generate professional copy with AI" },
  { label: "All Themes & Presets", description: "Access every design theme and layout preset" },
  { label: "Portfolio Analytics", description: "Track visitors and engagement" },
  { label: "Priority Support", description: "Get help when you need it" },
];
